# PAM look-up table
# The Wisecr server tool shall receive Vt from each CRFID device, and look-up this 
# table to acquire the corresponding active time and sleep time.
#
# VtUpper is the upper bound of applicable voltage of this row, if Vt is on the boundary, 
# use the value in this line.
#
# For example, the Vt received is 2180 mV.
# Check first line 2180 < 65535, check the second line 2180 < 2193, check the third
# line 2180 < 2183, check the fourth line 2180 !< 2143, then select the third line.
# pick ActiveTime = 14 and SleepTime = 15 and send to the device.
#
PAMTable = [
    { VtUpper = 65535, ActiveTime = -1, SleepTime = 0  },
    { VtUpper = 2193,  ActiveTime = 29, SleepTime = 10 },
    { VtUpper = 2183,  ActiveTime = 14, SleepTime = 15 },
    { VtUpper = 2143,  ActiveTime = 11, SleepTime = 25 },
    { VtUpper = 2140,  ActiveTime = 9,  SleepTime = 30 },
]

[Tag.WISP_PILOT]
TagId = 0xAA00
DeviceKey = [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
Valid = true
Done = false
TempOffset = 5.0
TempDivisor = 1000.0

[Tag.WISP_235]
TagId = 0x0235
DeviceKey = [0x69, 0xd0, 0xa9, 0x7c, 0xef, 0x92, 0x4e, 0xaf, 0x67, 0xe9, 0xbe, 0x25, 0x4d, 0x8d, 0x7f, 0x08]
Valid = true
Done = false

[Tag.WISP_237]
TagId = 0x0237
DeviceKey = [0x70, 0x73, 0x20, 0x69, 0x6e, 0x74, 0x6f, 0x20, 0x74, 0x68, 0x65, 0x20, 0x63, 0x6f, 0x64, 0x65]
Valid = true
Done = false

[Tag.WISP_238]
TagId = 0x0238
DeviceKey = [0xc0, 0x79, 0x9f, 0x06, 0x27, 0xa5, 0x21, 0x0f, 0x10, 0x2a, 0xd9, 0xd4, 0x0f, 0xb8, 0x6b, 0x32]
Valid = false
Done = false

[Tag.WISP_239]
TagId = 0x0239
DeviceKey = [0x4d, 0x24, 0x02, 0xe8, 0x3e, 0x2c, 0x8b, 0x8b, 0x08, 0x81, 0x23, 0x9c, 0xae, 0xc8, 0x7d, 0x25]
Valid = false
Done = false

[Tag.WISP_240]
TagId = 0x0240
DeviceKey = [0x77, 0x6f, 0x6d, 0x65, 0x6e, 0x79, 0x6f, 0x6e, 0x67, 0x79, 0x75, 0x61, 0x6e, 0x68, 0x75, 0x61]
Valid = false
Done = false

[Tag.WISP_241]
TagId = 0x0241
DeviceKey = [0x70, 0x6c, 0x6f, 0x6b, 0x69, 0x6d, 0x6a, 0x75, 0x6e, 0x68, 0x79, 0x62, 0x67, 0x74, 0x76, 0x66]
Valid = false
Done = false

[Tag.WISP_242]
TagId = 0x0242
DeviceKey = [0x31, 0x71, 0x32, 0x77, 0x33, 0x65, 0x34, 0x72, 0x35, 0x74, 0x36, 0x79, 0x37, 0x75, 0x38, 0x69]
Valid = false
Done = false
